### PR TITLE
feature: add AdvancedChatDisplay

### PR DESCRIPTION
**Pull request by Maastrich**

### CODE REVIEW

**Comment by jess-sys** [comment]
You could have split the chat part and skeleton, it's a messy review!

**Review by Drosaca — APPROVED** [review]

**Review by Drosaca — APPROVED** [review]

**Review by jess-sys — APPROVED** [review]
messy but ok

**Comment by jess-sys** [comment]
image
is this normal tho ?

**Comment by jess-sys** [comment]
image

**Comment by jess-sys** [comment]
image

**Comment by jess-sys** [comment]
image

**Comment by jess-sys** [comment]
I like the UI. Great work.

**Comment by Maastrich** [comment]
Breaking Changes merged through #47 an other

**Pull request closed without merging**
