### PR TITLE
Implement UI components: Posts, Reactions, Reacted, Comments

### PR DESCRIPTION
**Pull request by jess-sys**
Issue https://github.com/super-bunny/d4data/issues/737

### CODE REVIEW

**Comment by jess-sys** [comment]
https://media.discordapp.net/attachments/398275183758016522/841444517395300383/unknown.png?width=1175&height=683

**Comment by jess-sys** [comment]
image

**Comment by jess-sys** [comment]
Missing advanced icons on reacted.
Missing reacted root entity display.

**Comment by jess-sys** [comment]
image
image
Add auto computation of icon and parent component

**Review by ThalusA — APPROVED** [review]

**Review by super-bunny — APPROVED** [review]
Manually tested. Working :heavy_check_mark:

**Review by ThalusA — APPROVED** [review]

**Pull request merged**
