### PR TITLE
Implement UI components: Whereabouts, Tasks, Connections 

### PR DESCRIPTION
**Pull request by super-bunny**

### CODE REVIEW

**Comment by jess-sys** [comment]
Cleaned the code a little. The whereabouts and connections components need a lot of work to avoid freezing the whole UI.

**Comment by jess-sys** [comment]
Tasks component is OK

**Comment by jess-sys** [comment]
@super-bunny I'll let you fix the Whereabouts/Connexions component.

**Comment by jess-sys** [comment]
Note: sometimes the map shows the markers AFTER clicking on the Table tab

**Comment by jess-sys** [comment]
Conflicts from dev/ fixed.

**Comment by jess-sys** [comment]
image

**Comment by jess-sys** [comment]
image
image
image
image
image

**Review by jess-sys — DISMISSED** [review]

**Review by jess-sys — APPROVED** [review]

**Review by jess-sys — APPROVED** [review]

**Review by jess-sys — DISMISSED** [review]

**Review by jess-sys — APPROVED** [review]

**Review by ThalusA — DISMISSED** [review]

**Review by super-bunny — COMMENTED** [review]
Unfinished.
- can not scroll connection list
- task page display a sidebar over the app's sidebar
- task items don't respect parent width when there are long descriptions

**Comment by jess-sys** [comment]
image

fixed

**Comment by jess-sys** [comment]
image
respects parent width

**Comment by jess-sys** [comment]
image
fixed: can scroll to show all elements

**Comment by jess-sys** [comment]
Merging.

**Pull request merged**
